development:
  adapter: sqlite3
  database: db/reactive-gems-prod.sqlite3

development:
  adapter: sqlite3
  database: db/reactive-gems-dev.sqlite3

test:
  adapter: sqlite3
  database: db/reactive-gems-test.sqlite3
